### ISSUE TITLE
Data pre-2006?

### ISSUE THREAD

**Issue by Shpam** [danielkorzekwa/tennis-probability-calculator#1]
Hi,

Is there anyway you could put a csv up (or add) of the match data for pre-2006 matches?  I realize that it isn't entirely relevant for calculating probabilities of matches between current players but I think it might make it interesting to try and calculate probabilities between old and new players.

**Comment by danielkorzekwa** [comment]
My atp api software stopped working, probably because of some changes to
the atp website, and I have no time to make it working againg. Sorry.
